import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);let chromium;try{({chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'));}catch{}
const source=fs.readFileSync(new URL('./pack-ui.mjs',import.meta.url),'utf8'),css=fs.readFileSync(new URL('./pack.css',import.meta.url),'utf8');
test('pack chooser fits phone and desktop screens and imports only checked tracks',{skip:!chromium},async()=>{
 const browser=await chromium.launch({headless:true});try{const page=await browser.newPage();await page.route('**/*',r=>r.request().url().endsWith('/pack-ui.mjs')?r.fulfill({contentType:'text/javascript',body:source}):r.fulfill({contentType:'text/html',body:'<!doctype html><html><head></head><body style="margin:0"></body></html>'}));await page.goto('http://pack.test/');await page.addStyleTag({content:css});
 const entries=JSON.parse(fs.readFileSync(new URL('./catalog.json',import.meta.url),'utf8')).filter(e=>e.packId==='tmnf-ab'),pack=JSON.parse(fs.readFileSync(new URL('./packs.json',import.meta.url),'utf8'))[0];
 await page.evaluate(async({entries,pack})=>{const m=await import('/pack-ui.mjs');window.packImports=[];window.pack=m.mountTrackPack({document,root:document.body,entries,pack,onImport:async e=>window.packImports.push(e.id)});},{entries,pack});
 for(const [width,height] of [[320,720],[390,844],[844,390],[1366,768],[2800,1920]]){await page.setViewportSize({width,height});const m=await page.evaluate(()=>({width:document.querySelector('.pt-pack-dialog').getBoundingClientRect().width,scroll:document.querySelector('.pt-pack-dialog').scrollWidth,client:document.querySelector('.pt-pack-dialog').clientWidth}));assert.ok(m.width<=width+.5);assert.ok(m.scroll<=m.client+1);}
 await page.setViewportSize({width:1366,height:768});await page.getByRole('button',{name:'Select none',exact:true}).click();const boxes=page.locator('.pt-pack-checkbox');await boxes.nth(0).check();await boxes.nth(3).check();await page.locator('.pt-pack-import').click();await page.waitForFunction(()=>window.packImports.length===2);assert.deepEqual(await page.evaluate(()=>window.packImports),[entries[0].id,entries[3].id]);await page.getByRole('button',{name:'Close',exact:true}).click();assert.equal(await page.locator('.pt-pack-overlay').count(),0);
 }finally{await browser.close();}
});
